[database]
    name     = "vulcanize_public"
    hostname = "localhost"
    port     = 5432
    password = "password"
    user     = "vdbm"

[validate]
    blockHeight = 1
    trail  = 16
    sleepInterval = 10
    stateDiffMissingBlock = true
    stateDiffTimeout = 240

[ethereum]
    chainConfig = ""
    chainID = "1"
    httpPath = "localhost:8545"

[prom]
    metrics = true
    http = true
    httpAddr = "localhost"
    httpPort = "9001"
    dbStats = true

[log]
    file = ""
    level = "info"
