[database]
    name     = "vulcanize_public"
    hostname = "localhost"
    port     = 5432
    password = "password"
    user     = "vdbm"

[validate]
    block-height = 1
    trail  = 10
    sleepInterval = 5

[ethereum]
    chainConfig = "./chain.json"
