[database]
    name     = "vulcanize_public"
    hostname = "localhost"
    port     = 5432
    password = "password"
    user     = "vdbm"

[validate]
    block-height = 1
    trail  = 16
    sleepInterval = 10
    stateDiffOnMiss = true
    stateDiffTimeout = 60

[ethereum]
    chainConfig = "./chain.json"
    httpPath = "localhost:8545"

[prom]
    metrics = true
    http = true
    httpAddr = "localhost"
    httpPort = "9001"
    dbStats = true
