[database]
    name     = "cerc_public"
    hostname = "localhost"
    port     = 5432
    password = "password"
    user     = "vdbm"

[validate]
    fromHeight = 1
    trail = 16
    retryInterval = "10s"
    stateDiffMissingBlock = true
    stateDiffTimeout = "240s"

[ethereum]
    chainConfig = ""
    chainID = "1"
    httpPath = "localhost:8545"
    wsPath = "localhost:8546"

[prom]
    metrics = true
    http = true
    httpAddr = "localhost"
    httpPort = "9001"
    dbStats = true

[log]
    file = ""
    level = "info"
