name: Test the stack.
on:
  workflow_call:

env:
  STACK_ORCHESTRATOR_REF: 382aca8e42bc5e33f301f77cdd2e09cc80602fc3
  GO_ETHEREUM_REF: "v1.10.18-statediff-4.0.2-alpha"

jobs:
  integrationtest:
    name: Run integration tests
    env:
      GOPATH: /tmp/go
      DB_WRITE: true
    runs-on: ubuntu-latest
    steps:
      - name: Create GOPATH
        run: mkdir -p /tmp/go
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
          check-latest: true
      - uses: actions/checkout@v2
        with:
          path: "./ipld-eth-db-validator"
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.STACK_ORCHESTRATOR_REF }}
          path: "./stack-orchestrator/"
          repository: vulcanize/stack-orchestrator
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.GO_ETHEREUM_REF }}
          repository: vulcanize/go-ethereum
          path: "./go-ethereum/"
      - name: Create config file
        run: |
          echo vulcanize_go_ethereum=$GITHUB_WORKSPACE/go-ethereum/ >> ./config.sh
          echo vulcanize_test_contract=$GITHUB_WORKSPACE/ipld-eth-db-validator/test/contract >> ./config.sh
          echo db_write=$DB_WRITE >> ./config.sh
          cat ./config.sh
      - name: Build geth
        run: |
          cd $GITHUB_WORKSPACE/stack-orchestrator/helper-scripts
          ./compile-geth.sh \
          -p "$GITHUB_WORKSPACE/config.sh" \
          -e docker
      - name: Run docker compose
        run: |
          docker-compose  \
          -f "$GITHUB_WORKSPACE/stack-orchestrator/docker/latest/docker-compose-db-sharding.yml" \
          -f "$GITHUB_WORKSPACE/stack-orchestrator/docker/local/docker-compose-go-ethereum.yml" \
          -f "$GITHUB_WORKSPACE/stack-orchestrator/docker/local/docker-compose-contract.yml" \
          --env-file "$GITHUB_WORKSPACE/config.sh" \
          up -d --build
      - name: Run integration test.
        run: |
          cd $GITHUB_WORKSPACE/ipld-eth-db-validator
          ./scripts/run_integration_test.sh

  unittest:
    name: Run unit tests
    env:
      GOPATH: /tmp/go
      DB_WRITE: true
    runs-on: ubuntu-latest
    steps:
      - name: Create GOPATH
        run: mkdir -p /tmp/go
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
          check-latest: true
      - uses: actions/checkout@v2
        with:
          path: "./ipld-eth-db-validator"
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.STACK_ORCHESTRATOR_REF }}
          path: "./stack-orchestrator/"
          repository: vulcanize/stack-orchestrator
      - name: Run docker compose
        run: |
          docker-compose  \
          -f "$GITHUB_WORKSPACE/stack-orchestrator/docker/latest/docker-compose-db-sharding.yml" \
          up -d --build
      - name: Run unit test.
        run: |
          cd $GITHUB_WORKSPACE/ipld-eth-db-validator
          PGPASSWORD=password DATABASE_USER=vdbm DATABASE_PORT=8077 DATABASE_PASSWORD=password DATABASE_HOSTNAME=127.0.0.1 DATABASE_NAME=vulcanize_testing make test
