name: Unit and integration tests
on:
  workflow_call:

jobs:
  unit-tests:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: "Run DB container"
        run: |
          docker compose -f test/compose-db.yml up --wait --quiet-pull
      - name: "Run tests"
        run: |
          go test -v ./pkg/...

  integration-tests:
    name: "Run integration tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: "Install stack-orchestrator"
        # FIXME: using my dev branch for v5 migration changes until a release has them
        uses: actions/checkout@v3
        with:
          repository: cerc-io/stack-orchestrator
          ref: roy/for-ci
          path: ./stack-orchestrator
      - run: pip install ./stack-orchestrator
      - name: "Run testnet stack"
        run: ./scripts/integration-setup.sh
      - name: "Run contract deployer"
        env:
          ETH_CHAIN_ID: ${{ env.ETH_CHAIN_ID }}
          DEPLOYER_PRIVATE_KEY: ${{ env.DEPLOYER_PRIVATE_KEY }}
          ETH_HTTP_PATH: ${{ env.ETH_HTTP_PATH }}
        run: |
          set -x
          docker compose -f test/compose-deployer.yml up --wait --quiet-pull

          # height=$(./scripts/get-block-number.sh $ETH_HTTP_PATH)
          # [[ $height < 2 ]] && exit 1

          export ETH_HTTP_PATH
          timeout 2m bash -c '
          set -x
          while
              height=$(./scripts/get-block-number.sh $ETH_HTTP_PATH)
              [[ "$height" < 2 ]];
          do sleep 1; done
          '
          echo VALIDATE_FROM_HEIGHT=$height >> "$GITHUB_ENV"
      - name: "Run tests"
        env:
          ETH_CHAIN_CONFIG: ${{ env.ETH_CHAIN_CONFIG }}
          VALIDATE_FROM_HEIGHT: ${{ env.VALIDATE_FROM_HEIGHT }}
        run: |
          go test -v ./integration/...
      - uses: mxschmitt/action-tmate@v3 # XXX dev
        if: ${{ failure() }}
